name: Generate Snake

on:
  schedule: # a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    name: Gera a animação da cobrinha
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#d95f5f&color_dots=#161b22,#3a1a1a,#5f2828,#8a4141,#d95f5f
            dist/github-snake-light.svg?palette=github-light&color_snake=#a83f3f&color_dots=#e2e0d6,#ddb9b9,#c47e7e,#8a4141,#6b2828

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
